---
uaa/cloudfoundry-identity-varz-1.0.2.war:
  object_id: 1a0e5866-f1ae-46f2-a519-a74b9adb0003
  sha: 8c35ed35fb6dfc4a97a243447763c635812066e8
  size: 5727747
uaa/newrelic.jar:
  object_id: 97012cfa-58e4-4a2d-8a22-9be557e980ee
  sha: a5070963fc84bea27acc1d492cb9e3143f0c4715
  size: 7064901
uaa/cloudfoundry-identity-statsd-1.0.0.war:
  object_id: 928a8aca-a8f0-4036-aa0c-804c463fc895
  sha: c26a49ef1c8c5d6b215bf57ca6267e4d7f9f1a53
  size: 11163253
openjdk/openjdk-1.8.0_91-x86_64-trusty.tar.gz:
  object_id: a0aeff72-54ff-424c-acc2-a8844ea930f9
  sha: 69c612c7f783aad33f4d73ec9b44e1a2ee50f386
  size: 78278698
openjdk/openjdk-1.8.0_91-x86_64-mountainlion.tar.gz:
  object_id: 515f6add-b3b4-46ac-abc8-378d81514032
  sha: 9e916262cf92d6ca0b09f9261d30aeca05f214d7
  size: 75516939
postgres/postgresql-9.4.6.tar.gz:
  object_id: 83e927a9-2d85-4d80-bf20-50cf5020ed3f
  sha: bd031beebd86bf149c497525dccf57eebe5a6add
  size: 23249307
uaa/apache-tomcat-7.0.68.tar.gz:
  object_id: 1b2c6101-34af-473e-bc17-d830f2b663aa
  sha: 3e8481f74968d80cb9cb0b7ca1a0ed40e4a707e7
  size: 8900822
