bellsoft-11.0.24+9.tar.gz:
  size: 215952524
  object_id: 219232e4-b11d-471a-6a18-c4b802461020
  sha: sha256:d0bedc485d79f66fe20eb748c5944d52a1ed8a7b753bcb7a8953e7cc8bc7bdf2
uaa/apache-tomcat-9.0.95.tar.gz:
  size: 12715996
  object_id: 2870e4ee-50ea-452b-6fce-bca786bcdf19
  sha: sha256:5b375a9e34a5cb05df2188bfe9e2b6a6f7b691a3c0a626b2b4c047c51d434205
uaa/newrelic.jar:
  size: 38587449
  object_id: 92e6515f-081a-41cd-536e-1e18db865f6d
  sha: sha256:30a48502cbaeda36954b06559b484de96506ada6a525fe57ef6bbba72fa7d106
