bellsoft-11.0.15+10.tar.gz:
  size: 207498462
  object_id: 792e4e1d-d8c3-44ca-7f31-7c1912621188
  sha: sha256:c7d9d4963313466687ece0730a1e4d7d7fd7683f8cae546316d21112b1858e90
uaa/apache-tomcat-9.0.62.tar.gz:
  size: 11560971
  object_id: 4d296fcb-9b30-4766-7fe4-2bc1a5ef6e1d
  sha: sha256:03157728a832cf9c83048cdc28d09600cbb3e4fa087f8b97d74c8b4f34cd89bb
uaa/newrelic.jar:
  size: 22227615
  object_id: 66ce9b8c-def7-429d-7050-dd4c95ec36da
  sha: sha256:44e4a78b8b5526e3b7fbe5e46fee50a0decad3355aa007117a056e30bdcb6a8a
