openjdk/openjdk-1.8.0_202-x86_64-mountainlion.tar.gz:
  size: 101468874
  object_id: 75e918ce-effa-44b0-7771-76cae4c235e7
  sha: 8b1c4f973ea4d4b5876431a3b58728ea6b3dea6e
openjdk/openjdk-1.8.0_202-x86_64-trusty.tar.gz:
  size: 103343856
  object_id: 3dd729c1-c064-45c3-40c9-26f6450d2519
  sha: 8ae76b80ffd1be54f43cf3490e6e1a871fc88e8e
postgres/postgresql-11.1.tar.gz:
  size: 28078799
  object_id: b1461def-d2af-43b4-69ee-e9b7c7a5f26c
  sha: 5f3e45d5ad5ec3372474eda83e6441ca885ab2cd
uaa/apache-tomcat-9.0.13.tar.gz:
  size: 9988120
  object_id: 491f73e0-5965-422e-6116-9c71d1679f43
  sha: e57f860069cf5a0d0fee2c958671a5f4df71d3e6
uaa/newrelic.jar:
  size: 10612298
  object_id: dcb04454-dc24-497b-4926-908456c10fc8
  sha: 239f655f63233b9ba403d85b5a652d5c75957fb2
